move how to play to homepage and playing game page
sFractal-Podii/quizquadaminos pull request #85
Opened 2021-03-04 08:56 UTC by WanjikuMac

closes #53

2021-03-05 01:07 UTC, sparrell requested changes
I get errors when running.
When I hit space bar, it returns to home page.
The error in the logs is
** (UndefinedFunctionError) function QuadquizaminosWeb.Router.Helpers.live_path/2 is undefined or private "
I’m not that good at reading the logs but another message that goes with it is
(quadquizaminos 0.3.4) lib/quadquizaminos_web/live/tetris_live.ex:66: anonymous fn/2 in QuadquizaminosWeb.TetrisLive.render/1 "

2021-03-07 04:40 UTC, WanjikuMac commented
@sparrell the bug is fixed you can test again, let me know which instructions from the readme should go to the how-to play page

2021-03-07 16:43 UTC, sparrell commented
I have tested and am fine with it. Note the PR is still 'draft' and also note it has merge conflicts. Fix the conflicts and take off the draft and I'm OK. Wrt "which instructions from the readme should go to the how-to play page", I'm ok with leaving as is for now. We'll update the instuctions as we add more features.

2021-03-07 16:44 UTC, sparrell approved these changes

2021-03-08 20:41 UTC, merged